# permissions for end users to edit nifis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifi-editor-role
rules:
- apiGroups:
  - bigdata.quay.io
  resources:
  - nifis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.quay.io
  resources:
  - nifis/status
  verbs:
  - get
