---
apiVersion: bigdata.quay.io/v1alpha1
kind: Nifi
metadata:
  name: test
spec:
  size: 1
  useDefaultCredentials: true
  console:
    expose: true
    protocol: "http"
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "4"
      memory: "4Gi"
